#!/bin/bash

if [ "$1" == "inc" ]
then
	amixer -q sset Master 5%+

	if [ $2 ]
	then 
		vol=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }')
		notify-send "Volume" "$vol"
	fi;
elif [ "$1" == "dec" ]
then
	amixer -q sset Master 5%-

	if [ $2 ]
	then
		vol=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }')
		notify-send "Volume" "$vol"
	fi;
else
	amixer -q sset Master toggle

	if [ $2 ]
	then
		vol=
		vol=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $4 }')
		notify-send "Volume" "$vol"
	fi;
fi;

